default:
  tags:
    - docker

stages:
  - checks
  - build
  - test

.checks:
  stage: checks
  image: registry.esss.lu.se/ecdc/ess-dmsc/docker-ubuntu2204-build-node:latest

clang-format:
  extends: .checks
  script:
    - jenkins-scripts/check-formatting.sh  # TODO Rename directory

black:
  extends: .checks
  script:
    - python3 -m black --version
    - python3 -m black --check integration-tests

cppcheck:
  extends: .checks
  script:
    - cppcheck --version
    - >
      cppcheck \
        --xml \
        --inline-suppr \
        --suppress=unusedFunction \
        --suppress=missingInclude \
        --enable=all \
        --inconclusive \
        src/ 2> cppcheck.xml
  only:
    - merge_requests

build:
  stage: build
  image: registry.esss.lu.se/ecdc/ess-dmsc/docker-$DISTRIBUTION-build-node:latest
  script:
    - mkdir build
    - cd build
    - $SCL conan install --build missing ..
    - $SCL cmake -DCONAN=MANUAL ..
    - $SCL make -j 4
  parallel:
    matrix:
      - DISTRIBUTION: centos7
        SCL: scl enable devtoolset-11 --
      - DISTRIBUTION:
          - debian11
          - ubuntu2204

build-release:
  stage: build
  image: registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-build-node:latest
  script:
    - mkdir build
    - cd build
    - scl enable devtoolset-11 -- conan install --build missing ..
    - scl enable devtoolset-11 -- ../jenkins-scripts/configure-release.sh .. .
