fixes:
  - "kafka-to-nexus/::"  # Corrects coverage paths to be relative to repo root

ignore:
  - "src/tests"
  - "system-tests/"

comment:
  layout: "header, diff, tree, changes, sunburst"
  require_changes: false

coverage:
  status:
    patch:
      default:
        # basic
        target: auto
        threshold: 5