version: '2'

services:

    kafka:
      image: wurstmeister/kafka:0.11.0.1
      depends_on:
        - zookeeper
      hostname: kafka
      restart: unless-stopped
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_MESSAGE_MAX_BYTES: 10000000
        KAFKA_BROKER_ID: 0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    zookeeper:
      image: zookeeper:3.4
      restart: unless-stopped
      ports:
        - '2181:2181'

    manager:
      image: sheepkiller/kafka-manager:alpine
      depends_on:
        - zookeeper
        - kafka
      ports:
        - "9000:9000"
      environment:
        ZK_HOSTS: zookeeper:2181

    file-writer:
      build: .
      network_mode: "host"
      environment:
        COMMAND_URI: "//localhost:9092/TEST_writerCommand"
        STATUS_URI: "//localhost:9092/TEST_writerStatus"
        KAFKA_BROKER: "localhost"
