
software_dest: /opt/software
sources: '{{software_dest}}/sources'
builds:  '{{software_dest}}/builds'

flatbuffers_src: https://github.com/google/flatbuffers.git
flatbuffers_version: master
flatbuffers: '{{software_dest}}/flatbuffers-{{flatbuffers_version}}'

rapidjson_src: https://github.com/miloyip/rapidjson.git
rapidjson_version: master
rapidjson: '{{ software_dest }}/rapidjson-{{rapidjson_version}}'

rdkafka_src: https://github.com/edenhill/librdkafka.git
rdkafka_version: 0.9.4.x
rdkafka: '{{ software_dest }}/rdkafka-{{rdkafka_version}}'

streaming_data_types_src: https://github.com/ess-dmsc/streaming-data-types.git
streaming_data_types_version: master
streaming_data_types: '{{software_dest}}/streaming-data-types-{{streaming_data_types_version}}'

hdf5_src: ftp://ftp.hdfgroup.org/HDF5/current/src/
hdf5_version: 1.10.1
hdf5: '{{software_dest}}/hdf5-{{hdf5_version}}'

fmt_src: https://github.com/fmtlib/fmt.git
fmt_version: master
fmt: '{{software_dest}}/fmt-{{fmt_version}}'

filewriter_src: https://github.com/ess-dmsc/kafka-to-nexus.git
filewriter_version: master
filewriter: '{{software_dest}}/kafka-to-nexus'

filewriter_inc: '"{{hdf5}}/include;{{flatbuffers}}/include;{{rapidjson}}/include;{{rdkafka}}/include;{{streaming_data_types}};{{fmt}}"'
filewriter_lib: '"{{hdf5}}/lib;{{flatbuffers}}/lib;{{rdkafka}}/lib;{{fmt}}"'
filewriter_bin: '{{flatbuffers}}/bin'

use_stow: false

