version: "2"
services:
  zookeeper:
    extends:
      file: docker-common.yml
      service: zookeeper
  wait_for_zookeeper:
    extends:
      file: docker-common.yml
      service: wait_for_zookeeper
    depends_on:
      - zookeeper
  kafka:
    extends:
      file: docker-common.yml
      service: kafka
    depends_on:
      - wait_for_zookeeper
  filewriter1:
    image: filewriter-image:latest
    hostname: filewriter1
    depends_on:
      - kafka
    environment:
      CONFIG_FILE: "/file_writer_config.ini"
      LOG_FILE: "/filewriter_logs/filewriter_1.log"
    volumes:
      - ./config-files/file_writer_config.ini:/file_writer_config.ini
      - ./output-files/:/output-files/
      - ./logs/:/filewriter_logs/
  filewriter2:
    image: filewriter-image:latest
    hostname: filewriter2
    depends_on:
      - kafka
    environment:
      CONFIG_FILE: "/file_writer_config.ini"
      LOG_FILE: "/filewriter_logs/filewriter_2.log"
    volumes:
      - ./config-files/file_writer_config.ini:/file_writer_config.ini
      - ./output-files/:/output-files/
      - ./logs/:/filewriter_logs/
