version: "2"
services:
  ioc:
    image: screamingudder/softioc:latest
    stdin_open: true
    tty: true
    network_mode: "host"

  forwarder:
    image: screamingudder/forwarder:e9f7241
    network_mode: "host"
    depends_on:
      - ioc
    environment:
      CONFIG_FILE: "/forwarder_config_lr.ini"
      KAFKA_BROKER: "localhost"
    volumes:
      - ./config-files/forwarder_config_lr.ini:/forwarder_config_lr.ini
      - ./config-files/forwarder_command_lr.json:/forwarder_command_lr.json

