version: '2'

services:
  filewriter:
    depends_on:
      - event-producer
    image: kafka-to-nexus:latest
    network_mode: "host"
    environment:
      CONFIG_FILE: "/file_writer_config.ini"
    volumes:
      - ./config-files/file_writer_config.ini:/file_writer_config.ini
      - ./output-files/:/output-files/
      - ./logs/:/filewriter_logs/
