version: '2'

services:
  filewriter1:
    image: filewriter-image:latest
    network_mode: "host"
    environment:
      CONFIG_FILE: "/file_writer_config.ini"
      LOG_FILE: "/filewriter_logs/filewriter_1.log"
    volumes:
      - ./config-files/file_writer_config.ini:/file_writer_config.ini
      - ./output-files/:/output-files/
      - ./logs/:/filewriter_logs/
  filewriter2:
    image: filewriter-image:latest
    network_mode: "host"
    environment:
      CONFIG_FILE: "/file_writer_config.ini"
      LOG_FILE: "/filewriter_logs/filewriter_2.log"
    volumes:
      - ./config-files/file_writer_config.ini:/file_writer_config.ini
      - ./output-files/:/output-files/
      - ./logs/:/filewriter_logs/
