---

- stat:
    path: "{{hdf5}}"
  register: st

- name: Download hdf5
  unarchive:
    src: "{{hdf5_src}}/hdf5-{{hdf5_version}}.tar.gz"
    dest: "{{sources}}"
    remote_src: True
  when: not st.stat.exists

- name: Create build folder
  file:
    path: "{{builds}}/hdf5-{{hdf5_version}}"
    state: directory
  when: not st.stat.exists

- name: Configure hdf5
  command: "cmake -DBUILD_SHARED_LIBS:BOOL=TRUE -DCMAKE_INSTALL_PREFIX={{hdf5}} {{sources}}/hdf5-{{hdf5_version}}"
  args:
    chdir: "{{builds}}/hdf5-{{hdf5_version}}"
  when: not st.stat.exists

- name: Compile and install hdf5
  make:
    target: install
    chdir: "{{builds}}/hdf5-{{hdf5_version}}"
    params:
      NUM_THREADS: 4
  when: not st.stat.exists
