version: "3.5"

services:
  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:7.4.3
    deploy:
      resources:
        limits:
          memory: 600M
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    networks:
      - frontend
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 300000000
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 300000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 300000000
      KAFKA_LOG_RETENTION_MS: -1  # keep data forever, required for tests involving fake "historical" data
      ## listeners
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:7.4.3
    deploy:
      resources:
        limits:
          memory: 200M
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - frontend

  filewriter:
    container_name: filewriter
    image: registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-build-node:latest
    depends_on:
      kafka:
        condition: service_healthy
    tty: true
    networks:
      - frontend

networks:
  frontend:
