version: "2"
services:
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    hostname: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 300000000
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 300000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 300000000
      KAFKA_BROKER_ID: 0
      KAFKA_LOG_RETENTION_MS: -1  # keep data forever, required for tests involving fake "historical" data
      KAFKA_CREATE_TOPICS: "TEST_epicsConnectionStatus:1:1,TEST_sampleEnv:1:1,TEST_writer_jobs:1:1,TEST_writer_commands:1:1,TEST_writer_commands_alternative:1:1,TEST_forwarderConfig:1:1,TEST_forwarderStatusLR:1:1,TEST_forwarderDataLR:1:1"
    depends_on:
      - wait_for_zookeeper

  zookeeper:
    image: zookeeper:3.8.0

  wait_for_zookeeper:
    image: dadarek/wait-for-dependencies
    command: zookeeper:2181
    depends_on:
      - zookeeper
